### ISSUE TITLE
Modrinth - Failed to create version

### ISSUE THREAD

**Issue by Rushmead** [modmuss50/mod-publish-plugin#1]
When uploading a new version to Modrinth, the request fails with "Failed to create version" and no other information.

Stacktrace is attached.

Gradle files: https://github.com/theatricalmod/Theatrical/blob/1.19.2-alpha/fabric/build.gradle & https://github.com/theatricalmod/Theatrical/blob/1.19.2-alpha/forge/build.gradle

I grabbed my access token for Modrinth from my account settings page. 

[stacktrace.txt](https://github.com/modmuss50/mod-publish-plugin/files/12101022/stacktrace.txt)

**Comment by modmuss50** [comment]
Thanks, should be fixed with: https://github.com/modmuss50/mod-publish-plugin/commit/5a36c39ce08587f97914347db78e78092875dfec

**Comment by Rushmead** [comment]
Perfect thanks, all working now!
