### ISSUE TITLE
'gameVersions' metadata is less than minimum length (1)

### ISSUE THREAD

**Issue by ApexModder** [modmuss50/mod-publish-plugin#12]
[_Continued from #11_](https://github.com/modmuss50/mod-publish-plugin/issues/11#issuecomment-1670178069)

ok that fixed that issue but.... now we have a new issue, it wants an array of length 1 minimum
```
> Task :fabric:publishCurseforge FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fabric:publishCurseforge'.
> A failure occurred while executing me.modmuss50.mpp.platforms.curseforge.Curseforge$UploadWorkAction
   > Request failed, status: 400 message: Error in field `metadata`:
     * Array item count 0 is less than minimum count of 1. Path 'gameVersions', line 1, position 132.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

**Comment by ApexModder** [comment]
This seems to be related to `additionalFiles` as those are being uploaded with an `emptyList`

https://github.com/modmuss50/mod-publish-plugin/blob/1368039fea48934d1fa802f93865d00219ed5db7/src/main/kotlin/me/modmuss50/mpp/platforms/curseforge/Curseforge.kt#L131-L133

changing this to use the same set of `gameVersions`, seems to fix this issue from my local-testing

```diff
--- a/src/main/kotlin/me/modmuss50/mpp/platforms/curseforge/Curseforge.kt
+++ b/src/main/kotlin/me/modmuss50/mpp/platforms/curseforge/Curseforge.kt
@@ -129,7 +129,7 @@ abstract class Curseforge @Inject constructor(name: String) : Platform(name), Cu
         }

         for (additionalFile in additionalFiles.files) {
-            val additionalMetadata = metadata.copy(parentFileID = response.id, gameVersions = emptyList())
+            val additionalMetadata = metadata.copy(parentFileID = response.id)

             val additionalResponse = HttpUtils.retry(maxRetries.get(), "Failed to upload additional file") {
                 api.uploadFile(projectId.get(), additionalFile.toPath(), additionalMetadata)
```

**Comment by modmuss50** [comment]
Yeah, sorry about this. I have had a few attempts at fixing this, first https://github.com/modmuss50/mod-publish-plugin/commit/8c97a305d0c443cebe5f775bf7009dce8e689057 and https://github.com/modmuss50/mod-publish-plugin/commit/1368039fea48934d1fa802f93865d00219ed5db7

I have been a bit lazy and tried to fix it without testing, the curseforge documentation is not clear at all about the expected behaviour here. I will find some time to figure this out.

**Comment by ApexModder** [comment]
yeah, I have been trying to implement a fix myself but this kinda feels like some issue in CurseForge's API?
- If you specify `parentFileID`, `gameVersions` is unsupported and should not be specified.
- They want `gameVersions` to always exist and contain at least 1 entry, but this goes against how `parentFileID` works.
These 2 rules in the API, feel like they contradict each other, making it impossible to upload parented files to CurseForge.
