### ISSUE TITLE
Publishing fails silently if the files are present in the builds/libs folder

### ISSUE THREAD

**Issue by Edivad99** [modmuss50/mod-publish-plugin#15]
I launched the `publishMods` command when the jar and apiJar files of my mod were inside the `build/libs` folder. Once completed I went to modrinth and the files hadn't uploaded.
I tried deleting the files inside the folder and re-running the command and the upload was successful.

**Comment by modmuss50** [comment]
I have tried to reproduce this and I am unable to. If the task is being ran (can you check the log to make sure it is?) and is successful I see no reason for it to not work.

**Comment by Edivad99** [comment]
I tried again and now it works. I don't know, maybe I did something wrong...
