### ISSUE TITLE
Additional files should maybe use file names rather than gradle display name property

### ISSUE THREAD

**Issue by ApexModder** [modmuss50/mod-publish-plugin#19]
When uploading multiple files to CurseForge they are all given the exact same display name, this makes additional files hard to identify.

In the below screenshot i have uploaded 5 additional jar files, as our mod is setup to be modular.

![image](https://github.com/modmuss50/mod-publish-plugin/assets/29412632/f5b9e780-fe69-454b-b679-7e5669324f51)

These are a collection of sources jars aswell as individual modual jars for players to change which modules are installed.

They are as follows
- `fantasyfurniture-nordic-fabric-10.0.51+1.20.2-sources.jar`
- `fantasyfurniture-nordic-fabric-10.0.51+1.20.2.jar`
- `fantasyfurniture-complete-fabric-10.0.51+1.20.2-sources.jar`
- `fantasyfurniture-fabric-10.0.51+1.20.2-sources.jar`
- `fantasyfurniture-fabric-10.0.51+1.20.2.jar`

As you can see it is hard to identify which of these files is which, without digging further into the file and looking at the file name property.

---

This is not a problem when it comes to Modrinth as they just list the additional files using the raw file name.

<details>

![image](https://github.com/modmuss50/mod-publish-plugin/assets/29412632/f6532aa9-3168-4c4f-a68a-c6be86a83c62)

</details>

**Comment by modmuss50** [comment]
Good idea, I guess the ideal option would be to also provide an API to allow this name to be changed. Not too sure how feasible/easy that would be however.

**Comment by ApexModder** [comment]
Would it be possible to merge my [band-aid fix](https://github.com/ApexModder/mod-publish-plugin/commit/ef3505a2c30b79eb58453bcff4e2122d8c3df99d) until some api is implemented?

This would nullify the display name and let curseforge internal handle the naming, which defaults to the uploaded file name. Not the best but its better than everything having the exact same name.

I ask as updates/releases for our mod shave been put on hold until this is fixed, as our most popular mod has gone a more modular route and knowing which file is which is kind of an important thing (for advanced installs at least).

**Comment by modmuss50** [comment]
@ApexModder yeah, I am quite happy to merge your fix now (can you make it a PR?).

And yeah, something along those lines is what im thinking, ill try and find some time to figure that out.

**Comment by modmuss50** [comment]
I ended up creating a PR from your branch and releasing as `0.3.6`

**Comment by ApexModder** [comment]
Can confirm latest update did fix this issue for me, [See my release here](https://legacy.curseforge.com/minecraft/mc-mods/fantasys-furniture/files/4784486) and the [gradle here](https://github.com/ApexStudios-Dev/FantasyFurniture/blob/fdc1373dee8c2e25aad154de5e6603325bbd9208/projects/complete/fabric/build.gradle#L104-L158)

**Comment by modmuss50** [comment]
This was fixed.
