### ISSUE TITLE
Ability to target specific mod versions for dependencies

### ISSUE THREAD

**Issue by IThundxr** [modmuss50/mod-publish-plugin#21]
With other tools like minotaur or curseforgegradle you can target a exact version of a mod to set as a dependency.
This would be pretty cool to have here

**Comment by modmuss50** [comment]
I dont see a way to do this with the curseforge API. 🤔 If there is its not documented.

**Comment by IThundxr** [comment]
Uhhh I think curseforge doesn't support that but modrinth does?

**Comment by modmuss50** [comment]
Turns out I already added this, but never documented it. I have now added it to the documentation website. Thanks.
