### ISSUE TITLE
`minecraftVersionRange` throws if either the start or end is a snapshot.

### ISSUE THREAD

**Issue by AnAwesomGuy** [modmuss50/mod-publish-plugin#33]
So basically, `MinecraftApi#getVersionsInRange` throws if `includeSnapshots` is false and either the start or end versions are not releases.

I'm suggesting that if `includeSnapshots` is false and either the start or end versions are not releases, instead of throwing, it should just get the next release _after_ that snapshot. Hopefully this shouldn't be hard to implement.

**Comment by modmuss50** [comment]
Whats the reasoning/use case behind this?

**Comment by AnAwesomGuy** [comment]
as you can see [here](https://github.com/AnAwesomGuy/wsmlmb/blob/1.19.3-1.19.4/gradle.properties#L18-L20), i have a version range in my `gradle.properties` and i use it for publishing stuff and in my `fabric.mod.json`
the version range fails on curseforge, as it contains a snapshot
i could always access `MinecraftApi` manually and get the releases by myself, but it would be best if you could do this

**Comment by modmuss50** [comment]
Im not too keen on this idea, curseforge only has a basic concept of snapshots.

**Comment by AnAwesomGuy** [comment]
It would just skip over the snapshots and ignore them, not add them to `minecraftVersions`.

**Comment by modmuss50** [comment]
As I said before I am not a massive fan of this idea, curseforge doesnt have a concept of snapshots so I dont think the version rage for it should do either.
