### ISSUE TITLE
Request failed, status: 404 message: Unknown error during upload of fabric version to modrinth

### ISSUE THREAD

**Issue by Erdragh** [modmuss50/mod-publish-plugin#43]
See these two failed runs:
- https://github.com/Erdragh/AstralBot/actions/runs/9305548495/job/25612742557
- https://github.com/Erdragh/AstralBot/actions/runs/9265436311/job/25487466524

And this successful dry run:
https://github.com/Erdragh/AstralBot/actions/runs/9265192916/job/25486723128

**Comment by Erdragh** [comment]
This was caused by me using the wrong slug for the forge-config-api-port on Modrinth. However, a more meaningful Error message would have been helpful.

**Comment by AnAwesomGuy** [comment]
see https://github.com/modmuss50/mod-publish-plugin/blob/a5f1d8d65cfe924c813678324dce99b301824840/src/main/kotlin/me/modmuss50/mpp/platforms/modrinth/ModrinthApi.kt#L164
when the error code from modrinth api has no description, unknown error is provided
