### ISSUE TITLE
Issue with :publishModrinth

### ISSUE THREAD

**Issue by Xelbayria** [modmuss50/mod-publish-plugin#45]
```
* What went wrong:
Could not add entry ':publishModrinth' to cache executionHistory.bin (~\1.18.2\WoodGood\.gradle\7.4\executionHistory\executionHistory.bin).
> Cannot encode a null string.
```

I had no problem with Curseforge using dryRun. and I can't figure what's the problem with Modrinth??

My script is 
```gradle
    modrinth {
        projectId = "myprojectID" // i've included the id (shouldn't be an issue) 
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        minecraftVersions.add("${minecraft_version}")
        requires("moonlight")
    }
```

**Comment by modmuss50** [comment]
Please can you try with a newer Gradle version? 8.3 or later is what I test with.

**Comment by Xelbayria** [comment]
8.3?? oh  I thought 5.3 or so is the latest. will test.

**Comment by Xelbayria** [comment]
ok i tested it with Gradle 8.3 and it's working. I was using 7.4. It's my first time using Gradle and mod-publish. Thanks for helping out.  

one more thing i would like to know how to make `Display name: MyMod-1.18.2-1.16.13`  into `Display name: ___`

just blank.
