### ISSUE TITLE
Error 403 when trying to upload mods to CurseForge

### ISSUE THREAD

**Issue by LopyMine** [modmuss50/mod-publish-plugin#62]
Honestly, I don't know why it happens

Here is my very simple publish settings
![image](https://github.com/user-attachments/assets/551a4fc1-0d7f-4271-8a04-cf8d838c4fce)

And I got this error while running `publishMods`

![image](https://github.com/user-attachments/assets/daca62c2-c044-42e6-8aca-27fb7c3c9f1f)

Tell me if you need more information

**Comment by modmuss50** [comment]
Hi, a 403 error from curseforge indicates that your access token may be incorrect, or you are being blocked for another reason.

**Comment by LopyMine** [comment]
So, access token cannot be incorrect, then it seems like I'm blocked for some reason, which is definitely strange, because it doesn't work with enabled VPN too. Also I just tried to use token from new account (still with VPN), and it also doesn't work... 

Well, I'm going to write CurseForge support about it

**Comment by modmuss50** [comment]
Ill close this issue, im glad you figured it out. Your best solution might be to use Github actions, this way you can trigger the buid from the Github UI and then then plugin will upload it from Github's own servers.
